### ISSUE TITLE
Use within a template variable

### ISSUE THREAD

**Issue by ryanbuiltthat** [frozeman/meteor-inline-form#1]
Is it possible to populate parameters with template variables?

For example:

`{{> InlineForm name="{{_id}}" value="{{body}}"/}}`

**Comment by codetheweb** [comment]
@frozeman I'm having this same problem.  Is there a solution/way around this?

**Comment by ryanbuiltthat** [comment]
Never got around to trying to hack together a solution for this. It'd be nice though. If I have time I'll try to wrap an existing library up as a package.

**Comment by frozeman** [comment]
what you're suggesting is no possible with meteor, as it doesn't support `{{ {{}} }}`, but you can simply do:

``` js
{{> InlineForm name=_id value=body}}
```

**Comment by codetheweb** [comment]
Ah, many thanks @frozeman.  Didn't know you could do that.  Works perfectly now.
